{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.fresco",
    "module": "middleware",
    "version": "3.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "middleware-3.6.0.aar",
          "url": "middleware-3.6.0.aar",
          "size": 6534,
          "sha512": "d32cf6bf1ab6628b485c9a338255820e21c68bf4d19f4cf06828891a1181471102c9a3b47c27089e7e50e24595740ed18ef3fb363eb14f537609754378037dd0",
          "sha256": "9661f47cb1156a0a7246819802c9b017ba5170f6ae7abedf31fd2cf662e3dc10",
          "sha1": "5a98865d88dddc49d9e8e24c096d0542527e762b",
          "md5": "cd51b9023adced7a873381a28e29021c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "middleware-3.6.0.aar",
          "url": "middleware-3.6.0.aar",
          "size": 6534,
          "sha512": "d32cf6bf1ab6628b485c9a338255820e21c68bf4d19f4cf06828891a1181471102c9a3b47c27089e7e50e24595740ed18ef3fb363eb14f537609754378037dd0",
          "sha256": "9661f47cb1156a0a7246819802c9b017ba5170f6ae7abedf31fd2cf662e3dc10",
          "sha1": "5a98865d88dddc49d9e8e24c096d0542527e762b",
          "md5": "cd51b9023adced7a873381a28e29021c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "middleware-3.6.0-sources.jar",
          "url": "middleware-3.6.0-sources.jar",
          "size": 2426,
          "sha512": "4a64e0886443feed9ed2a1f708854e417faa4c179ead3c1f0e5e09f3609fed3f3b33b4eeca2b9094189f1e6b39e7065773565b688d59d7cccb8418fd7af8698c",
          "sha256": "ae66bb55e4c0dd8ae374f30e13d210ec1072808955e6d49ca216d521508c0cfa",
          "sha1": "3566e711a01a15b8a1cf2f9b3befe05b39c7056f",
          "md5": "b1cfdd09cf9b4723f3ed8d471c7c0455"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "middleware-3.6.0-javadoc.jar",
          "url": "middleware-3.6.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
