{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.fresco",
    "module": "imagepipeline-okhttp3",
    "version": "3.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.14.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "imagepipeline-okhttp3-3.6.0.aar",
          "url": "imagepipeline-okhttp3-3.6.0.aar",
          "size": 13935,
          "sha512": "aa676abb8e2453d0441cc30b2a07819061786ddcc2674e35492565bea5a8a5acb50f5b5ee6639c6d84662b661b83960c7f760068d4aedf9e8c0dd691af61b931",
          "sha256": "faa01ed0394a5ec86cfe9c06e106a32179e4fb8378e7aeefde58321594ba6593",
          "sha1": "f75658406fc40624534f34f2037bd9c3ed24b7d1",
          "md5": "d98f6a279095a03bd61ace8f151246b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-native",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-ashmem",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-native",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-java",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "middleware",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.14.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "imagepipeline-okhttp3-3.6.0.aar",
          "url": "imagepipeline-okhttp3-3.6.0.aar",
          "size": 13935,
          "sha512": "aa676abb8e2453d0441cc30b2a07819061786ddcc2674e35492565bea5a8a5acb50f5b5ee6639c6d84662b661b83960c7f760068d4aedf9e8c0dd691af61b931",
          "sha256": "faa01ed0394a5ec86cfe9c06e106a32179e4fb8378e7aeefde58321594ba6593",
          "sha1": "f75658406fc40624534f34f2037bd9c3ed24b7d1",
          "md5": "d98f6a279095a03bd61ace8f151246b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imagepipeline-okhttp3-3.6.0-sources.jar",
          "url": "imagepipeline-okhttp3-3.6.0-sources.jar",
          "size": 4890,
          "sha512": "6aa2beb30c438b759ea19ef3c406113fc61932c0681e9e4c0ab7099816075694d7d6315b7804add8dc8a96a6c4eb1e01a1b7e12117746b6c2957b3a98f465275",
          "sha256": "b07bca7e5b7cf5f1e50da44992ac4d310cab242d3c40c00b6de189acab3c56be",
          "sha1": "bafdd1c1464fe4e3316b2ed302467fcbf4087063",
          "md5": "4e46cda78492aa363df7d922e58b3d5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imagepipeline-okhttp3-3.6.0-javadoc.jar",
          "url": "imagepipeline-okhttp3-3.6.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
