{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.fresco",
    "module": "urimod",
    "version": "3.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "urimod-3.6.0.aar",
          "url": "urimod-3.6.0.aar",
          "size": 16584,
          "sha512": "87806cf84abed169683245f04db1a14ebac1820a7819c58440eff5c94a6d28d4008400f6dbcbd138e771ed6e86cb40a6cca9ba7fae33a9ef5e56404909bcd059",
          "sha256": "54bc0886e579eb0833297492b7d89cb4c613ca95c379bacc41adfe29539a91f7",
          "sha1": "c9d3e49bb328f8ac90812607569db1c4817a2b4e",
          "md5": "e7347c4e8de065ce11a6d96159fe92f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "vito-source",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "urimod-3.6.0.aar",
          "url": "urimod-3.6.0.aar",
          "size": 16584,
          "sha512": "87806cf84abed169683245f04db1a14ebac1820a7819c58440eff5c94a6d28d4008400f6dbcbd138e771ed6e86cb40a6cca9ba7fae33a9ef5e56404909bcd059",
          "sha256": "54bc0886e579eb0833297492b7d89cb4c613ca95c379bacc41adfe29539a91f7",
          "sha1": "c9d3e49bb328f8ac90812607569db1c4817a2b4e",
          "md5": "e7347c4e8de065ce11a6d96159fe92f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "urimod-3.6.0-sources.jar",
          "url": "urimod-3.6.0-sources.jar",
          "size": 3126,
          "sha512": "25fdf341111f0c7dd371f9e24853331f065683efe455462717eca5d3a22274c2fdeccfb2a75c9132cb78532ba5d1334eada92e03cf4b99399995aa823e9eb135",
          "sha256": "fb4dbd9dc896ad74db4616414ad175e04588f11463152db934f50d2b304e6389",
          "sha1": "6ac822d353b9551963f4b3eb59bed520a3c6f9e5",
          "md5": "284a42236f33c98a57addce1073ac958"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "urimod-3.6.0-javadoc.jar",
          "url": "urimod-3.6.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
