{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.fresco",
    "module": "drawee",
    "version": "3.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.fresco",
          "module": "ui-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "drawee-3.6.0.aar",
          "url": "drawee-3.6.0.aar",
          "size": 133887,
          "sha512": "f49288ce6bd2595eaabc12475d33a04beea6dd06f77839a949354599dbb926416cefb53f794b5c14be3a647e0b4433913779686c98ade852e7326ee8b9238c76",
          "sha256": "60435519cb76cee78739d928c46aada918f76cb993b75af92ab17e9d746b0277",
          "sha1": "e9d30af378cb2b632af3e35c021e391f0de501b0",
          "md5": "9a457589239a5b3d015b964887ad121a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-native",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-ashmem",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-native",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-java",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "middleware",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "drawee-3.6.0.aar",
          "url": "drawee-3.6.0.aar",
          "size": 133887,
          "sha512": "f49288ce6bd2595eaabc12475d33a04beea6dd06f77839a949354599dbb926416cefb53f794b5c14be3a647e0b4433913779686c98ade852e7326ee8b9238c76",
          "sha256": "60435519cb76cee78739d928c46aada918f76cb993b75af92ab17e9d746b0277",
          "sha1": "e9d30af378cb2b632af3e35c021e391f0de501b0",
          "md5": "9a457589239a5b3d015b964887ad121a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "drawee-3.6.0-sources.jar",
          "url": "drawee-3.6.0-sources.jar",
          "size": 97345,
          "sha512": "8347a82bbc0f6f089e7a22a62332c80b1d5c8c5d802e2060722ab1fe572083f7ded7e4e2ebb0d34473869bb67332364a7ecc0577de2288dc6c5e24f44543754c",
          "sha256": "b51089c11947e75be832c83011b15474099326c71545c47c8c8a59e8961a4c63",
          "sha1": "f02b0f30614449dfed7855fd693fb29c274b1322",
          "md5": "8f447892ac9689bcd77ceeeccef894ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "drawee-3.6.0-javadoc.jar",
          "url": "drawee-3.6.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
