{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.fresco",
    "module": "imagepipeline",
    "version": "3.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-base",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "imagepipeline-3.6.0.aar",
          "url": "imagepipeline-3.6.0.aar",
          "size": 525282,
          "sha512": "503eb9f1f4c82b5e42c38246be94661dd5a46004fb3d57822c0754dcc72d9c3d97069a97fc05e238da893fb000af945ae03c975727097f56baa236686ac0328e",
          "sha256": "57f04195e5d7273671ce467d0e23c487b3c2c8746ac6257f2a2753cc0771f69f",
          "sha1": "4219ff1555b833fdef37a35a6b702361a9525309",
          "md5": "0446c31a0f2ca27c168b580c0be32a38"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.soloader",
          "module": "nativeloader",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "annotation",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "com.parse.bolts",
          "module": "bolts-tasks",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "middleware",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "urimod",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-base",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "imagepipeline-3.6.0.aar",
          "url": "imagepipeline-3.6.0.aar",
          "size": 525282,
          "sha512": "503eb9f1f4c82b5e42c38246be94661dd5a46004fb3d57822c0754dcc72d9c3d97069a97fc05e238da893fb000af945ae03c975727097f56baa236686ac0328e",
          "sha256": "57f04195e5d7273671ce467d0e23c487b3c2c8746ac6257f2a2753cc0771f69f",
          "sha1": "4219ff1555b833fdef37a35a6b702361a9525309",
          "md5": "0446c31a0f2ca27c168b580c0be32a38"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imagepipeline-3.6.0-sources.jar",
          "url": "imagepipeline-3.6.0-sources.jar",
          "size": 268360,
          "sha512": "8085c4c8be7f057b700eb9174a516f54738633a4aa8b2962a28039b2856fa6261b56ba0dfd616d89a5fbe0609389a30a45f3e9b027cef51092d57462de804c0f",
          "sha256": "e473ae66088b2618f9e3844aa482861b3083819646dc27fe42272e0da210e403",
          "sha1": "03c54c95887a211f7519b865344a8d54f6f453c6",
          "md5": "16918d31bee338d753e645995f31b8c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imagepipeline-3.6.0-javadoc.jar",
          "url": "imagepipeline-3.6.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
