{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.fresco",
    "module": "nativeimagefilters",
    "version": "3.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nativeimagefilters-3.6.0.aar",
          "url": "nativeimagefilters-3.6.0.aar",
          "size": 53565,
          "sha512": "a883402aa976fe26ece716f8cf0af1026159fccb393becc5c603ca9985d174a7f52beb3e5cc6c889ff8bb97a38e0dfabee9f9e7ffe42db47d1e5078c4f57f4ef",
          "sha256": "5044745e85fb35177e8e2b80df82c02a968a6db88affe711e4fb0038924d32bd",
          "sha1": "62fe003ddbda2d53eef46ae46c52c5bdca71879a",
          "md5": "77253121bc0666b662424802c5f32ac2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-native",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-ashmem",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-native",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-java",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "nativeloader",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "com.parse.bolts",
          "module": "bolts-tasks",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "nativeimagefilters-3.6.0.aar",
          "url": "nativeimagefilters-3.6.0.aar",
          "size": 53565,
          "sha512": "a883402aa976fe26ece716f8cf0af1026159fccb393becc5c603ca9985d174a7f52beb3e5cc6c889ff8bb97a38e0dfabee9f9e7ffe42db47d1e5078c4f57f4ef",
          "sha256": "5044745e85fb35177e8e2b80df82c02a968a6db88affe711e4fb0038924d32bd",
          "sha1": "62fe003ddbda2d53eef46ae46c52c5bdca71879a",
          "md5": "77253121bc0666b662424802c5f32ac2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nativeimagefilters-3.6.0-sources.jar",
          "url": "nativeimagefilters-3.6.0-sources.jar",
          "size": 6033,
          "sha512": "993d1ea75526c052ca9e2bd61f0db62f8888a9ee4cb1630b1240748f1e2edf43a93d13009f56b02d7e7419c1ccfc3ab293112eac651259cf2e5800d55ef4ccbf",
          "sha256": "23354b30fff9fd0340fd5cc1c7088c0e976b26716def4251bbc4da82538a896c",
          "sha1": "3f343984e09e6d769c5953350a122699cc6f94f3",
          "md5": "f50c25a7b204b61114bdf9ea1740394e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nativeimagefilters-3.6.0-javadoc.jar",
          "url": "nativeimagefilters-3.6.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
