{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.fresco",
    "module": "fbcore",
    "version": "3.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "fbcore-3.6.0.aar",
          "url": "fbcore-3.6.0.aar",
          "size": 144807,
          "sha512": "a16d419cc8b0e3cb8029a2390abf060495b2d33c9761ed0771fc1f02755e295bd1fcf2d00701c3166699433e8c0b65dff2a4fc1470a5a9abaa39342b4e34f0ef",
          "sha256": "6fd98c2b5737ee56a9c90f1c34d87d24e5d3324fd7fc2cca6d6e74b1c0b43ce9",
          "sha1": "c0fc44d0aa3d2c0052986c22fb58d564a779c835",
          "md5": "8eadaa739a61e6e6333f290ed12eda98"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "fbcore-3.6.0.aar",
          "url": "fbcore-3.6.0.aar",
          "size": 144807,
          "sha512": "a16d419cc8b0e3cb8029a2390abf060495b2d33c9761ed0771fc1f02755e295bd1fcf2d00701c3166699433e8c0b65dff2a4fc1470a5a9abaa39342b4e34f0ef",
          "sha256": "6fd98c2b5737ee56a9c90f1c34d87d24e5d3324fd7fc2cca6d6e74b1c0b43ce9",
          "sha1": "c0fc44d0aa3d2c0052986c22fb58d564a779c835",
          "md5": "8eadaa739a61e6e6333f290ed12eda98"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fbcore-3.6.0-sources.jar",
          "url": "fbcore-3.6.0-sources.jar",
          "size": 122512,
          "sha512": "4fd7e16d5312700314cdbe591b5a69bed311608352d0b4fcb1ef9d15126fbcec143b715af06f5b11e56a5450b58e5e0e84791f14a1b738a3ef1523cd0d0b7140",
          "sha256": "9e40c8fffd8eac571133917fb14c1c42b44e789bf5911831b47b7217296c14fb",
          "sha1": "9778b27d7baa86ce048353edc80c470eb46a76a5",
          "md5": "820d9f67c7248d3a28f5f19fb849ef4b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fbcore-3.6.0-javadoc.jar",
          "url": "fbcore-3.6.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
